### ISSUE TITLE
Converting SB2 to SWF

### ISSUE THREAD

**Issue by Prazma** [junebeetle/junebeetle.github.io#1]
What if scratchers were able to convert their previously converted SWF file back to SB2?

**Comment by junebeetle** [comment]
This can be done with a decompiler/disassembler like FFDec. No need to add the functionality to the converter. Besides, I don't think that most Scratchers would necessarily want people to be able to do that...

What do you think? I think I'll close this.

**Comment by Prazma** [comment]
Ok
