### ISSUE TITLE
SB2 to EXE converter suggestion

### ISSUE THREAD

**Issue by AmazingMech2418** [junebeetle/junebeetle.github.io#2]
Could you make something that can convert it to .exe files? I don't have the normal version of flash, but still want to be able to get .exe versions of scratch.

**Comment by junebeetle** [comment]
Not actively updating this anymore, but please see http://junebeetle.github.io/converter/executables for a manual way to convert from the SWF to EXE.

**Comment by AmazingMech2418** [comment]
@junebeetle I can't convert SWF to EXE since I don't have Flash Player. I also can't convert Scratch to SWF for the same reason.

**Comment by junebeetle** [comment]
What is there to prevent you from just downloading a Flash player in order to do the conversion? In theory, I could bundle the converter as an EXE by converting _it_ as described on that page, but I don't see the need to do that right now.

**Comment by AmazingMech2418** [comment]
I saw an issue saying that newer versions of Flash Player won't run. Also, I don't know how to download Flash Player.

**Comment by junebeetle** [comment]
Never heard of that being a problem, nor do you need a new version. See this page (again haha)  http://junebeetle.github.io/converter/executables as it also has instructions for downloading a standalone Flash Player. You can use that Flash Player to open the converter SWF file. Or, you can simply download a browser Flash Player and run the converter in the browser, from https://get.adobe.com/flashplayer/

**Comment by Prazma** [comment]
@amazinigmech2418 There is a method where you could make .EXE out of modified [Phosphorus](https://phosphorus.github.io) using [GitHub Electron](https://electronjs.org/)

You'll need to know how to do some HTML and JavaScript (maybe CSS if you want to customize the looks of the loading page and etc.)

Hope this works for you...
