### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by imaperson1060** [junebeetle/junebeetle.github.io#8]
Recently you started redirecting your website address to asentientbot.github.io. Now all of the stuff you had on the old website like projector tools are gone :( Do you plan on putting the old stuff onto the new website?

(Does this qualify as an issue?)

**Comment by junebeetle** [comment]
Hey! I did not realize that anyone still used those things. I'll try to get them up on the new site in a couple days. Sorry about this.

**Comment by imaperson1060** [comment]
It's fine.
